/**
 * Cloudiator REST Api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.2.0
 * Contact: daniel.baur@uni-ulm.de
 *
 * NOTE: This class is auto generated by the swagger code generator 2.3.0-SNAPSHOT.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */



#include "Api.h"

namespace io {
namespace github {
namespace cloudiator {
namespace rest {
namespace model {

Api::Api()
{
    m_ProviderName = utility::conversions::to_string_t("");
}

Api::~Api()
{
}

void Api::validate()
{
    // TODO: implement validation
}

web::json::value Api::toJson() const
{
    web::json::value val = web::json::value::object();

    val[utility::conversions::to_string_t("providerName")] = ModelBase::toJson(m_ProviderName);

    return val;
}

void Api::fromJson(web::json::value& val)
{
    setProviderName(ModelBase::stringFromJson(val[utility::conversions::to_string_t("providerName")]));
}

void Api::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t("."))
    {
        namePrefix += utility::conversions::to_string_t(".");
    }

    multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t("providerName"), m_ProviderName));
}

void Api::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t("."))
    {
        namePrefix += utility::conversions::to_string_t(".");
    }

    setProviderName(ModelBase::stringFromHttpContent(multipart->getContent(utility::conversions::to_string_t("providerName"))));
}

utility::string_t Api::getProviderName() const
{
    return m_ProviderName;
}


void Api::setProviderName(utility::string_t value)
{
    m_ProviderName = value;
    
}
}
}
}
}
}

