/**
 * Cloudiator REST Api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.2.0
 * Contact: daniel.baur@uni-ulm.de
 *
 * NOTE: This class is auto generated by the swagger code generator 2.3.0-SNAPSHOT.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/*
 * AttributeOptimization.h
 *
 * Refers to the attribute that should be optimized
 */

#ifndef IO_GITHUB_CLOUDIATOR_REST_MODEL_AttributeOptimization_H_
#define IO_GITHUB_CLOUDIATOR_REST_MODEL_AttributeOptimization_H_


#include "Optimization.h"
#include <cpprest/details/basic_types.h>

namespace io {
namespace github {
namespace cloudiator {
namespace rest {
namespace model {

/// <summary>
/// Refers to the attribute that should be optimized
/// </summary>
class  AttributeOptimization
    : public Optimization
{
public:
    AttributeOptimization();
    virtual ~AttributeOptimization();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    void fromJson(web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    void fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// AttributeOptimization members

    /// <summary>
    /// 
    /// </summary>
    utility::string_t getObjectiveClass() const;
    bool objectiveClassIsSet() const;
    void unsetObjectiveClass();
    void setObjectiveClass(utility::string_t value);
    /// <summary>
    /// 
    /// </summary>
    utility::string_t getObjectiveAttribute() const;
    bool objectiveAttributeIsSet() const;
    void unsetObjectiveAttribute();
    void setObjectiveAttribute(utility::string_t value);
    /// <summary>
    /// 
    /// </summary>
    utility::string_t getAggregation() const;
    bool aggregationIsSet() const;
    void unsetAggregation();
    void setAggregation(utility::string_t value);

protected:
    utility::string_t m_ObjectiveClass;
    bool m_ObjectiveClassIsSet;
    utility::string_t m_ObjectiveAttribute;
    bool m_ObjectiveAttributeIsSet;
    utility::string_t m_Aggregation;
    bool m_AggregationIsSet;
};

}
}
}
}
}

#endif /* IO_GITHUB_CLOUDIATOR_REST_MODEL_AttributeOptimization_H_ */
