/**
 * Cloudiator REST Api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.2.0
 * Contact: daniel.baur@uni-ulm.de
 *
 * NOTE: This class is auto generated by the swagger code generator 2.3.0-SNAPSHOT.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */



#include "CloudConfiguration.h"

namespace io {
namespace github {
namespace cloudiator {
namespace rest {
namespace model {

CloudConfiguration::CloudConfiguration()
{
    m_NodeGroup = utility::conversions::to_string_t("");
    m_NodeGroupIsSet = false;
    m_PropertiesIsSet = false;
}

CloudConfiguration::~CloudConfiguration()
{
}

void CloudConfiguration::validate()
{
    // TODO: implement validation
}

web::json::value CloudConfiguration::toJson() const
{
    web::json::value val = web::json::value::object();

    if(m_NodeGroupIsSet)
    {
        val[utility::conversions::to_string_t("nodeGroup")] = ModelBase::toJson(m_NodeGroup);
    }
    if(m_PropertiesIsSet)
    {
        val[utility::conversions::to_string_t("properties")] = ModelBase::toJson(m_Properties);
    }

    return val;
}

void CloudConfiguration::fromJson(web::json::value& val)
{
    if(val.has_field(utility::conversions::to_string_t("nodeGroup")))
    {
        setNodeGroup(ModelBase::stringFromJson(val[utility::conversions::to_string_t("nodeGroup")]));
    }
    if(val.has_field(utility::conversions::to_string_t("properties")))
    {
        if(!val[utility::conversions::to_string_t("properties")].is_null())
        {
            std::shared_ptr<Map> newItem(new Map());
            newItem->fromJson(val[utility::conversions::to_string_t("properties")]);
            setProperties( newItem );
        }
    }
}

void CloudConfiguration::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t("."))
    {
        namePrefix += utility::conversions::to_string_t(".");
    }

    if(m_NodeGroupIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t("nodeGroup"), m_NodeGroup));
        
    }
    if(m_PropertiesIsSet)
    {
        if (m_Properties.get())
        {
            m_Properties->toMultipart(multipart, utility::conversions::to_string_t("properties."));
        }
        
    }
}

void CloudConfiguration::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t("."))
    {
        namePrefix += utility::conversions::to_string_t(".");
    }

    if(multipart->hasContent(utility::conversions::to_string_t("nodeGroup")))
    {
        setNodeGroup(ModelBase::stringFromHttpContent(multipart->getContent(utility::conversions::to_string_t("nodeGroup"))));
    }
    if(multipart->hasContent(utility::conversions::to_string_t("properties")))
    {
        if(multipart->hasContent(utility::conversions::to_string_t("properties")))
        {
            std::shared_ptr<Map> newItem(new Map());
            newItem->fromMultiPart(multipart, utility::conversions::to_string_t("properties."));
            setProperties( newItem );
        }
    }
}

utility::string_t CloudConfiguration::getNodeGroup() const
{
    return m_NodeGroup;
}


void CloudConfiguration::setNodeGroup(utility::string_t value)
{
    m_NodeGroup = value;
    m_NodeGroupIsSet = true;
}
bool CloudConfiguration::nodeGroupIsSet() const
{
    return m_NodeGroupIsSet;
}

void CloudConfiguration::unsetNodeGroup()
{
    m_NodeGroupIsSet = false;
}

std::shared_ptr<Map> CloudConfiguration::getProperties() const
{
    return m_Properties;
}


void CloudConfiguration::setProperties(std::shared_ptr<Map> value)
{
    m_Properties = value;
    m_PropertiesIsSet = true;
}
bool CloudConfiguration::propertiesIsSet() const
{
    return m_PropertiesIsSet;
}

void CloudConfiguration::unsetProperties()
{
    m_PropertiesIsSet = false;
}

}
}
}
}
}

