/**
 * Cloudiator REST Api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.2.0
 * Contact: daniel.baur@uni-ulm.de
 *
 * NOTE: This class is auto generated by the swagger code generator 2.3.0-SNAPSHOT.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/*
 * DataSink.h
 *
 * Data Sink where the monitoring data will be reported to. 
 */

#ifndef IO_GITHUB_CLOUDIATOR_REST_MODEL_DataSink_H_
#define IO_GITHUB_CLOUDIATOR_REST_MODEL_DataSink_H_


#include "../ModelBase.h"

#include <cpprest/details/basic_types.h>
#include "Map.h"

namespace io {
namespace github {
namespace cloudiator {
namespace rest {
namespace model {

/// <summary>
/// Data Sink where the monitoring data will be reported to. 
/// </summary>
class  DataSink
    : public ModelBase
{
public:
    DataSink();
    virtual ~DataSink();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    void fromJson(web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    void fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// DataSink members

    /// <summary>
    /// 
    /// </summary>
    utility::string_t getType() const;
    bool typeIsSet() const;
    void unsetType();
    void setType(utility::string_t value);
    /// <summary>
    /// 
    /// </summary>
    std::shared_ptr<Map> getConfiguration() const;
    bool configurationIsSet() const;
    void unsetConfiguration();
    void setConfiguration(std::shared_ptr<Map> value);

protected:
    utility::string_t m_Type;
    bool m_TypeIsSet;
    std::shared_ptr<Map> m_Configuration;
    bool m_ConfigurationIsSet;
};

}
}
}
}
}

#endif /* IO_GITHUB_CLOUDIATOR_REST_MODEL_DataSink_H_ */
