/**
 * Cloudiator REST Api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.2.0
 * Contact: daniel.baur@uni-ulm.de
 *
 * NOTE: This class is auto generated by the swagger code generator 2.3.0-SNAPSHOT.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/*
 * IdentifierRequirement.h
 *
 * Subtype of Requirement 
 */

#ifndef IO_GITHUB_CLOUDIATOR_REST_MODEL_IdentifierRequirement_H_
#define IO_GITHUB_CLOUDIATOR_REST_MODEL_IdentifierRequirement_H_


#include <cpprest/details/basic_types.h>
#include "Requirement.h"

namespace io {
namespace github {
namespace cloudiator {
namespace rest {
namespace model {

/// <summary>
/// Subtype of Requirement 
/// </summary>
class  IdentifierRequirement
    : public Requirement
{
public:
    IdentifierRequirement();
    virtual ~IdentifierRequirement();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    void fromJson(web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    void fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// IdentifierRequirement members

    /// <summary>
    /// 
    /// </summary>
    utility::string_t getHardwareId() const;
    bool hardwareIdIsSet() const;
    void unsetHardwareId();
    void setHardwareId(utility::string_t value);
    /// <summary>
    /// 
    /// </summary>
    utility::string_t getLocationId() const;
    bool locationIdIsSet() const;
    void unsetLocationId();
    void setLocationId(utility::string_t value);
    /// <summary>
    /// 
    /// </summary>
    utility::string_t getImageId() const;
    bool imageIdIsSet() const;
    void unsetImageId();
    void setImageId(utility::string_t value);

protected:
    utility::string_t m_HardwareId;
    bool m_HardwareIdIsSet;
    utility::string_t m_LocationId;
    bool m_LocationIdIsSet;
    utility::string_t m_ImageId;
    bool m_ImageIdIsSet;
};

}
}
}
}
}

#endif /* IO_GITHUB_CLOUDIATOR_REST_MODEL_IdentifierRequirement_H_ */
