/**
 * Cloudiator REST Api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.2.0
 * Contact: daniel.baur@uni-ulm.de
 *
 * NOTE: This class is auto generated by the swagger code generator 2.3.0-SNAPSHOT.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */



#include "InstallationRequest.h"

namespace io {
namespace github {
namespace cloudiator {
namespace rest {
namespace model {

InstallationRequest::InstallationRequest()
{
    m_ToolsIsSet = false;
    m_NodeIsSet = false;
}

InstallationRequest::~InstallationRequest()
{
}

void InstallationRequest::validate()
{
    // TODO: implement validation
}

web::json::value InstallationRequest::toJson() const
{
    web::json::value val = web::json::value::object();

    {
        std::vector<web::json::value> jsonArray;
        for( auto& item : m_Tools )
        {
            jsonArray.push_back(ModelBase::toJson(item));
        }
        if(jsonArray.size() > 0)
        {
            val[utility::conversions::to_string_t("tools")] = web::json::value::array(jsonArray);
        }
    }
    if(m_NodeIsSet)
    {
        val[utility::conversions::to_string_t("node")] = ModelBase::toJson(m_Node);
    }

    return val;
}

void InstallationRequest::fromJson(web::json::value& val)
{
    {
        m_Tools.clear();
        std::vector<web::json::value> jsonArray;
        if(val.has_field(utility::conversions::to_string_t("tools")))
        {
        for( auto& item : val[utility::conversions::to_string_t("tools")].as_array() )
        {
            if(item.is_null())
            {
                m_Tools.push_back( std::shared_ptr<Tool>(nullptr) );
            }
            else
            {
                std::shared_ptr<Tool> newItem(new Tool());
                newItem->fromJson(item);
                m_Tools.push_back( newItem );
            }
        }
        }
    }
    if(val.has_field(utility::conversions::to_string_t("node")))
    {
        if(!val[utility::conversions::to_string_t("node")].is_null())
        {
            std::shared_ptr<Node> newItem(new Node());
            newItem->fromJson(val[utility::conversions::to_string_t("node")]);
            setNode( newItem );
        }
    }
}

void InstallationRequest::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t("."))
    {
        namePrefix += utility::conversions::to_string_t(".");
    }

    {
        std::vector<web::json::value> jsonArray;
        for( auto& item : m_Tools )
        {
            jsonArray.push_back(ModelBase::toJson(item));
        }
        
        if(jsonArray.size() > 0)
        {
            multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t("tools"), web::json::value::array(jsonArray), utility::conversions::to_string_t("application/json")));
        }
    }
    if(m_NodeIsSet)
    {
        if (m_Node.get())
        {
            m_Node->toMultipart(multipart, utility::conversions::to_string_t("node."));
        }
        
    }
}

void InstallationRequest::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t("."))
    {
        namePrefix += utility::conversions::to_string_t(".");
    }

    {
        m_Tools.clear();
        if(multipart->hasContent(utility::conversions::to_string_t("tools")))
        {

        web::json::value jsonArray = web::json::value::parse(ModelBase::stringFromHttpContent(multipart->getContent(utility::conversions::to_string_t("tools"))));
        for( auto& item : jsonArray.as_array() )
        {
            if(item.is_null())
            {
                m_Tools.push_back( std::shared_ptr<Tool>(nullptr) );
            }
            else
            {
                std::shared_ptr<Tool> newItem(new Tool());
                newItem->fromJson(item);
                m_Tools.push_back( newItem );
            }
        }
        }
    }
    if(multipart->hasContent(utility::conversions::to_string_t("node")))
    {
        if(multipart->hasContent(utility::conversions::to_string_t("node")))
        {
            std::shared_ptr<Node> newItem(new Node());
            newItem->fromMultiPart(multipart, utility::conversions::to_string_t("node."));
            setNode( newItem );
        }
    }
}

std::vector<std::shared_ptr<Tool>>& InstallationRequest::getTools()
{
    return m_Tools;
}

void InstallationRequest::setTools(std::vector<std::shared_ptr<Tool>> value)
{
    m_Tools = value;
    m_ToolsIsSet = true;
}
bool InstallationRequest::toolsIsSet() const
{
    return m_ToolsIsSet;
}

void InstallationRequest::unsetTools()
{
    m_ToolsIsSet = false;
}

std::shared_ptr<Node> InstallationRequest::getNode() const
{
    return m_Node;
}


void InstallationRequest::setNode(std::shared_ptr<Node> value)
{
    m_Node = value;
    m_NodeIsSet = true;
}
bool InstallationRequest::nodeIsSet() const
{
    return m_NodeIsSet;
}

void InstallationRequest::unsetNode()
{
    m_NodeIsSet = false;
}

}
}
}
}
}

