/**
 * Cloudiator REST Api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.2.0
 * Contact: daniel.baur@uni-ulm.de
 *
 * NOTE: This class is auto generated by the swagger code generator 2.3.0-SNAPSHOT.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */



#include "JobNew.h"

namespace io {
namespace github {
namespace cloudiator {
namespace rest {
namespace model {

JobNew::JobNew()
{
    m_Name = utility::conversions::to_string_t("");
    m_TasksIsSet = false;
    m_CommunicationsIsSet = false;
    m_RequirementsIsSet = false;
}

JobNew::~JobNew()
{
}

void JobNew::validate()
{
    // TODO: implement validation
}

web::json::value JobNew::toJson() const
{
    web::json::value val = web::json::value::object();

    val[utility::conversions::to_string_t("name")] = ModelBase::toJson(m_Name);
    {
        std::vector<web::json::value> jsonArray;
        for( auto& item : m_Tasks )
        {
            jsonArray.push_back(ModelBase::toJson(item));
        }
        if(jsonArray.size() > 0)
        {
            val[utility::conversions::to_string_t("tasks")] = web::json::value::array(jsonArray);
        }
    }
    {
        std::vector<web::json::value> jsonArray;
        for( auto& item : m_Communications )
        {
            jsonArray.push_back(ModelBase::toJson(item));
        }
        if(jsonArray.size() > 0)
        {
            val[utility::conversions::to_string_t("communications")] = web::json::value::array(jsonArray);
        }
    }
    {
        std::vector<web::json::value> jsonArray;
        for( auto& item : m_Requirements )
        {
            jsonArray.push_back(ModelBase::toJson(item));
        }
        if(jsonArray.size() > 0)
        {
            val[utility::conversions::to_string_t("requirements")] = web::json::value::array(jsonArray);
        }
    }

    return val;
}

void JobNew::fromJson(web::json::value& val)
{
    setName(ModelBase::stringFromJson(val[utility::conversions::to_string_t("name")]));
    {
        m_Tasks.clear();
        std::vector<web::json::value> jsonArray;
        if(val.has_field(utility::conversions::to_string_t("tasks")))
        {
        for( auto& item : val[utility::conversions::to_string_t("tasks")].as_array() )
        {
            if(item.is_null())
            {
                m_Tasks.push_back( std::shared_ptr<Task>(nullptr) );
            }
            else
            {
                std::shared_ptr<Task> newItem(new Task());
                newItem->fromJson(item);
                m_Tasks.push_back( newItem );
            }
        }
        }
    }
    {
        m_Communications.clear();
        std::vector<web::json::value> jsonArray;
        if(val.has_field(utility::conversions::to_string_t("communications")))
        {
        for( auto& item : val[utility::conversions::to_string_t("communications")].as_array() )
        {
            if(item.is_null())
            {
                m_Communications.push_back( std::shared_ptr<Communication>(nullptr) );
            }
            else
            {
                std::shared_ptr<Communication> newItem(new Communication());
                newItem->fromJson(item);
                m_Communications.push_back( newItem );
            }
        }
        }
    }
    {
        m_Requirements.clear();
        std::vector<web::json::value> jsonArray;
        if(val.has_field(utility::conversions::to_string_t("requirements")))
        {
        for( auto& item : val[utility::conversions::to_string_t("requirements")].as_array() )
        {
            if(item.is_null())
            {
                m_Requirements.push_back( std::shared_ptr<Requirement>(nullptr) );
            }
            else
            {
                std::shared_ptr<Requirement> newItem(new Requirement());
                newItem->fromJson(item);
                m_Requirements.push_back( newItem );
            }
        }
        }
    }
}

void JobNew::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t("."))
    {
        namePrefix += utility::conversions::to_string_t(".");
    }

    multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t("name"), m_Name));
    {
        std::vector<web::json::value> jsonArray;
        for( auto& item : m_Tasks )
        {
            jsonArray.push_back(ModelBase::toJson(item));
        }
        
        if(jsonArray.size() > 0)
        {
            multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t("tasks"), web::json::value::array(jsonArray), utility::conversions::to_string_t("application/json")));
        }
    }
    {
        std::vector<web::json::value> jsonArray;
        for( auto& item : m_Communications )
        {
            jsonArray.push_back(ModelBase::toJson(item));
        }
        
        if(jsonArray.size() > 0)
        {
            multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t("communications"), web::json::value::array(jsonArray), utility::conversions::to_string_t("application/json")));
        }
    }
    {
        std::vector<web::json::value> jsonArray;
        for( auto& item : m_Requirements )
        {
            jsonArray.push_back(ModelBase::toJson(item));
        }
        
        if(jsonArray.size() > 0)
        {
            multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t("requirements"), web::json::value::array(jsonArray), utility::conversions::to_string_t("application/json")));
        }
    }
}

void JobNew::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t("."))
    {
        namePrefix += utility::conversions::to_string_t(".");
    }

    setName(ModelBase::stringFromHttpContent(multipart->getContent(utility::conversions::to_string_t("name"))));
    {
        m_Tasks.clear();
        if(multipart->hasContent(utility::conversions::to_string_t("tasks")))
        {

        web::json::value jsonArray = web::json::value::parse(ModelBase::stringFromHttpContent(multipart->getContent(utility::conversions::to_string_t("tasks"))));
        for( auto& item : jsonArray.as_array() )
        {
            if(item.is_null())
            {
                m_Tasks.push_back( std::shared_ptr<Task>(nullptr) );
            }
            else
            {
                std::shared_ptr<Task> newItem(new Task());
                newItem->fromJson(item);
                m_Tasks.push_back( newItem );
            }
        }
        }
    }
    {
        m_Communications.clear();
        if(multipart->hasContent(utility::conversions::to_string_t("communications")))
        {

        web::json::value jsonArray = web::json::value::parse(ModelBase::stringFromHttpContent(multipart->getContent(utility::conversions::to_string_t("communications"))));
        for( auto& item : jsonArray.as_array() )
        {
            if(item.is_null())
            {
                m_Communications.push_back( std::shared_ptr<Communication>(nullptr) );
            }
            else
            {
                std::shared_ptr<Communication> newItem(new Communication());
                newItem->fromJson(item);
                m_Communications.push_back( newItem );
            }
        }
        }
    }
    {
        m_Requirements.clear();
        if(multipart->hasContent(utility::conversions::to_string_t("requirements")))
        {

        web::json::value jsonArray = web::json::value::parse(ModelBase::stringFromHttpContent(multipart->getContent(utility::conversions::to_string_t("requirements"))));
        for( auto& item : jsonArray.as_array() )
        {
            if(item.is_null())
            {
                m_Requirements.push_back( std::shared_ptr<Requirement>(nullptr) );
            }
            else
            {
                std::shared_ptr<Requirement> newItem(new Requirement());
                newItem->fromJson(item);
                m_Requirements.push_back( newItem );
            }
        }
        }
    }
}

utility::string_t JobNew::getName() const
{
    return m_Name;
}


void JobNew::setName(utility::string_t value)
{
    m_Name = value;
    
}
std::vector<std::shared_ptr<Task>>& JobNew::getTasks()
{
    return m_Tasks;
}

void JobNew::setTasks(std::vector<std::shared_ptr<Task>> value)
{
    m_Tasks = value;
    m_TasksIsSet = true;
}
bool JobNew::tasksIsSet() const
{
    return m_TasksIsSet;
}

void JobNew::unsetTasks()
{
    m_TasksIsSet = false;
}

std::vector<std::shared_ptr<Communication>>& JobNew::getCommunications()
{
    return m_Communications;
}

void JobNew::setCommunications(std::vector<std::shared_ptr<Communication>> value)
{
    m_Communications = value;
    m_CommunicationsIsSet = true;
}
bool JobNew::communicationsIsSet() const
{
    return m_CommunicationsIsSet;
}

void JobNew::unsetCommunications()
{
    m_CommunicationsIsSet = false;
}

std::vector<std::shared_ptr<Requirement>>& JobNew::getRequirements()
{
    return m_Requirements;
}

void JobNew::setRequirements(std::vector<std::shared_ptr<Requirement>> value)
{
    m_Requirements = value;
    m_RequirementsIsSet = true;
}
bool JobNew::requirementsIsSet() const
{
    return m_RequirementsIsSet;
}

void JobNew::unsetRequirements()
{
    m_RequirementsIsSet = false;
}

}
}
}
}
}

