/**
 * Cloudiator REST Api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.2.0
 * Contact: daniel.baur@uni-ulm.de
 *
 * NOTE: This class is auto generated by the swagger code generator 2.3.0-SNAPSHOT.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/*
 * Login.h
 *
 * Login information provided by the user to be authorized 
 */

#ifndef IO_GITHUB_CLOUDIATOR_REST_MODEL_Login_H_
#define IO_GITHUB_CLOUDIATOR_REST_MODEL_Login_H_


#include "../ModelBase.h"

#include "Tenant.h"
#include <cpprest/details/basic_types.h>

namespace io {
namespace github {
namespace cloudiator {
namespace rest {
namespace model {

/// <summary>
/// Login information provided by the user to be authorized 
/// </summary>
class  Login
    : public ModelBase
{
public:
    Login();
    virtual ~Login();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    void fromJson(web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    void fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// Login members

    /// <summary>
    /// EMail address of the user
    /// </summary>
    utility::string_t getEmail() const;
        void setEmail(utility::string_t value);
    /// <summary>
    /// 
    /// </summary>
    std::shared_ptr<Tenant> getTenant() const;
        void setTenant(std::shared_ptr<Tenant> value);
    /// <summary>
    /// Password of the user
    /// </summary>
    utility::string_t getPassword() const;
        void setPassword(utility::string_t value);

protected:
    utility::string_t m_Email;
        std::shared_ptr<Tenant> m_Tenant;
        utility::string_t m_Password;
    };

}
}
}
}
}

#endif /* IO_GITHUB_CLOUDIATOR_REST_MODEL_Login_H_ */
