/**
 * Cloudiator REST Api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.2.0
 * Contact: daniel.baur@uni-ulm.de
 *
 * NOTE: This class is auto generated by the swagger code generator 2.3.0-SNAPSHOT.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/*
 * Map.h
 *
 * A key - value type of Map using &lt;String, String&gt;. 
 */

#ifndef IO_GITHUB_CLOUDIATOR_REST_MODEL_Map_H_
#define IO_GITHUB_CLOUDIATOR_REST_MODEL_Map_H_


#include <cpprest/details/basic_types.h>
#include <map>

namespace io {
namespace github {
namespace cloudiator {
namespace rest {
namespace model {

/// <summary>
/// A key - value type of Map using &lt;String, String&gt;. 
/// </summary>
class  Map
    : public null<String, utility::string_t>
{
public:
    Map();
    virtual ~Map();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    void fromJson(web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    void fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// Map members


protected:
};

}
}
}
}
}

#endif /* IO_GITHUB_CLOUDIATOR_REST_MODEL_Map_H_ */
