/**
 * Cloudiator REST Api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.2.0
 * Contact: daniel.baur@uni-ulm.de
 *
 * NOTE: This class is auto generated by the swagger code generator 2.3.0-SNAPSHOT.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */



#include "MonitoringTarget.h"

namespace io {
namespace github {
namespace cloudiator {
namespace rest {
namespace model {

MonitoringTarget::MonitoringTarget()
{
    m_Type = utility::conversions::to_string_t("");
    m_Identifier = utility::conversions::to_string_t("");
    m_IdentifierIsSet = false;
}

MonitoringTarget::~MonitoringTarget()
{
}

void MonitoringTarget::validate()
{
    // TODO: implement validation
}

web::json::value MonitoringTarget::toJson() const
{
    web::json::value val = web::json::value::object();

    val[utility::conversions::to_string_t("type")] = ModelBase::toJson(m_Type);
    if(m_IdentifierIsSet)
    {
        val[utility::conversions::to_string_t("identifier")] = ModelBase::toJson(m_Identifier);
    }

    return val;
}

void MonitoringTarget::fromJson(web::json::value& val)
{
    setType(ModelBase::stringFromJson(val[utility::conversions::to_string_t("type")]));
    if(val.has_field(utility::conversions::to_string_t("identifier")))
    {
        setIdentifier(ModelBase::stringFromJson(val[utility::conversions::to_string_t("identifier")]));
    }
}

void MonitoringTarget::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t("."))
    {
        namePrefix += utility::conversions::to_string_t(".");
    }

    multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t("type"), m_Type));
    if(m_IdentifierIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t("identifier"), m_Identifier));
        
    }
}

void MonitoringTarget::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t("."))
    {
        namePrefix += utility::conversions::to_string_t(".");
    }

    setType(ModelBase::stringFromHttpContent(multipart->getContent(utility::conversions::to_string_t("type"))));
    if(multipart->hasContent(utility::conversions::to_string_t("identifier")))
    {
        setIdentifier(ModelBase::stringFromHttpContent(multipart->getContent(utility::conversions::to_string_t("identifier"))));
    }
}

utility::string_t MonitoringTarget::getType() const
{
    return m_Type;
}


void MonitoringTarget::setType(utility::string_t value)
{
    m_Type = value;
    
}
utility::string_t MonitoringTarget::getIdentifier() const
{
    return m_Identifier;
}


void MonitoringTarget::setIdentifier(utility::string_t value)
{
    m_Identifier = value;
    m_IdentifierIsSet = true;
}
bool MonitoringTarget::identifierIsSet() const
{
    return m_IdentifierIsSet;
}

void MonitoringTarget::unsetIdentifier()
{
    m_IdentifierIsSet = false;
}

}
}
}
}
}

