/**
 * Cloudiator REST Api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.2.0
 * Contact: daniel.baur@uni-ulm.de
 *
 * NOTE: This class is auto generated by the swagger code generator 2.3.0-SNAPSHOT.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */



#include "OperatingSystemFamily.h"

namespace io {
namespace github {
namespace cloudiator {
namespace rest {
namespace model {

OperatingSystemFamily::OperatingSystemFamily()
{
}

OperatingSystemFamily::~OperatingSystemFamily()
{
}

void OperatingSystemFamily::validate()
{
    // TODO: implement validation
}

web::json::value OperatingSystemFamily::toJson() const
{
    web::json::value val = web::json::value::object();


    return val;
}

void OperatingSystemFamily::fromJson(web::json::value& val)
{
}

void OperatingSystemFamily::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t("."))
    {
        namePrefix += utility::conversions::to_string_t(".");
    }

}

void OperatingSystemFamily::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t("."))
    {
        namePrefix += utility::conversions::to_string_t(".");
    }

}

}
}
}
}
}

