/**
 * Cloudiator REST Api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.2.0
 * Contact: daniel.baur@uni-ulm.de
 *
 * NOTE: This class is auto generated by the swagger code generator 2.3.0-SNAPSHOT.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */



#include "Platform.h"

namespace io {
namespace github {
namespace cloudiator {
namespace rest {
namespace model {

Platform::Platform()
{
    m_Name = utility::conversions::to_string_t("");
    m_Type = utility::conversions::to_string_t("");
    m_TypeIsSet = false;
    m_Endpoint = utility::conversions::to_string_t("");
    m_EndpointIsSet = false;
    m_Id = utility::conversions::to_string_t("");
    m_IdIsSet = false;
}

Platform::~Platform()
{
}

void Platform::validate()
{
    // TODO: implement validation
}

web::json::value Platform::toJson() const
{
    web::json::value val = web::json::value::object();

    val[utility::conversions::to_string_t("name")] = ModelBase::toJson(m_Name);
    if(m_TypeIsSet)
    {
        val[utility::conversions::to_string_t("type")] = ModelBase::toJson(m_Type);
    }
    val[utility::conversions::to_string_t("api")] = ModelBase::toJson(m_Api);
    val[utility::conversions::to_string_t("credential")] = ModelBase::toJson(m_Credential);
    if(m_EndpointIsSet)
    {
        val[utility::conversions::to_string_t("endpoint")] = ModelBase::toJson(m_Endpoint);
    }
    if(m_IdIsSet)
    {
        val[utility::conversions::to_string_t("id")] = ModelBase::toJson(m_Id);
    }

    return val;
}

void Platform::fromJson(web::json::value& val)
{
    setName(ModelBase::stringFromJson(val[utility::conversions::to_string_t("name")]));
    if(val.has_field(utility::conversions::to_string_t("type")))
    {
        setType(ModelBase::stringFromJson(val[utility::conversions::to_string_t("type")]));
    }
    std::shared_ptr<Api> newApi(new Api());
    newApi->fromJson(val[utility::conversions::to_string_t("api")]);
    setApi( newApi );
    std::shared_ptr<CloudCredential> newCredential(new CloudCredential());
    newCredential->fromJson(val[utility::conversions::to_string_t("credential")]);
    setCredential( newCredential );
    if(val.has_field(utility::conversions::to_string_t("endpoint")))
    {
        setEndpoint(ModelBase::stringFromJson(val[utility::conversions::to_string_t("endpoint")]));
    }
    if(val.has_field(utility::conversions::to_string_t("id")))
    {
        setId(ModelBase::stringFromJson(val[utility::conversions::to_string_t("id")]));
    }
}

void Platform::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t("."))
    {
        namePrefix += utility::conversions::to_string_t(".");
    }

    multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t("name"), m_Name));
    if(m_TypeIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t("type"), m_Type));
        
    }
    m_Api->toMultipart(multipart, utility::conversions::to_string_t("api."));
    m_Credential->toMultipart(multipart, utility::conversions::to_string_t("credential."));
    if(m_EndpointIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t("endpoint"), m_Endpoint));
        
    }
    if(m_IdIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t("id"), m_Id));
        
    }
}

void Platform::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t("."))
    {
        namePrefix += utility::conversions::to_string_t(".");
    }

    setName(ModelBase::stringFromHttpContent(multipart->getContent(utility::conversions::to_string_t("name"))));
    if(multipart->hasContent(utility::conversions::to_string_t("type")))
    {
        setType(ModelBase::stringFromHttpContent(multipart->getContent(utility::conversions::to_string_t("type"))));
    }
    std::shared_ptr<Api> newApi(new Api());
    newApi->fromMultiPart(multipart, utility::conversions::to_string_t("api."));
    setApi( newApi );
    std::shared_ptr<CloudCredential> newCredential(new CloudCredential());
    newCredential->fromMultiPart(multipart, utility::conversions::to_string_t("credential."));
    setCredential( newCredential );
    if(multipart->hasContent(utility::conversions::to_string_t("endpoint")))
    {
        setEndpoint(ModelBase::stringFromHttpContent(multipart->getContent(utility::conversions::to_string_t("endpoint"))));
    }
    if(multipart->hasContent(utility::conversions::to_string_t("id")))
    {
        setId(ModelBase::stringFromHttpContent(multipart->getContent(utility::conversions::to_string_t("id"))));
    }
}

utility::string_t Platform::getName() const
{
    return m_Name;
}


void Platform::setName(utility::string_t value)
{
    m_Name = value;
    
}
utility::string_t Platform::getType() const
{
    return m_Type;
}


void Platform::setType(utility::string_t value)
{
    m_Type = value;
    m_TypeIsSet = true;
}
bool Platform::typeIsSet() const
{
    return m_TypeIsSet;
}

void Platform::unsetType()
{
    m_TypeIsSet = false;
}

std::shared_ptr<Api> Platform::getApi() const
{
    return m_Api;
}


void Platform::setApi(std::shared_ptr<Api> value)
{
    m_Api = value;
    
}
std::shared_ptr<CloudCredential> Platform::getCredential() const
{
    return m_Credential;
}


void Platform::setCredential(std::shared_ptr<CloudCredential> value)
{
    m_Credential = value;
    
}
utility::string_t Platform::getEndpoint() const
{
    return m_Endpoint;
}


void Platform::setEndpoint(utility::string_t value)
{
    m_Endpoint = value;
    m_EndpointIsSet = true;
}
bool Platform::endpointIsSet() const
{
    return m_EndpointIsSet;
}

void Platform::unsetEndpoint()
{
    m_EndpointIsSet = false;
}

utility::string_t Platform::getId() const
{
    return m_Id;
}


void Platform::setId(utility::string_t value)
{
    m_Id = value;
    m_IdIsSet = true;
}
bool Platform::idIsSet() const
{
    return m_IdIsSet;
}

void Platform::unsetId()
{
    m_IdIsSet = false;
}

}
}
}
}
}

