/**
 * Cloudiator REST Api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.2.0
 * Contact: daniel.baur@uni-ulm.de
 *
 * NOTE: This class is auto generated by the swagger code generator 2.3.0-SNAPSHOT.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/*
 * PlatformInterface.h
 *
 * Subtype of TaskInterface Represents a PaaS interface 
 */

#ifndef IO_GITHUB_CLOUDIATOR_REST_MODEL_PlatformInterface_H_
#define IO_GITHUB_CLOUDIATOR_REST_MODEL_PlatformInterface_H_


#include <cpprest/details/basic_types.h>
#include "TaskInterface.h"

namespace io {
namespace github {
namespace cloudiator {
namespace rest {
namespace model {

/// <summary>
/// Subtype of TaskInterface Represents a PaaS interface 
/// </summary>
class  PlatformInterface
    : public TaskInterface
{
public:
    PlatformInterface();
    virtual ~PlatformInterface();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    void fromJson(web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    void fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// PlatformInterface members

    /// <summary>
    /// URL to the source code repository (currently only git is supported) 
    /// </summary>
    utility::string_t getSourceRepository() const;
    bool sourceRepositoryIsSet() const;
    void unsetSourceRepository();
    void setSourceRepository(utility::string_t value);

protected:
    utility::string_t m_SourceRepository;
    bool m_SourceRepositoryIsSet;
};

}
}
}
}
}

#endif /* IO_GITHUB_CLOUDIATOR_REST_MODEL_PlatformInterface_H_ */
