/**
 * Cloudiator REST Api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.2.0
 * Contact: daniel.baur@uni-ulm.de
 *
 * NOTE: This class is auto generated by the swagger code generator 2.3.0-SNAPSHOT.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/*
 * Platform.h
 *
 * Representation of a platform used by Cloudiator
 */

#ifndef IO_GITHUB_CLOUDIATOR_REST_MODEL_Platform_H_
#define IO_GITHUB_CLOUDIATOR_REST_MODEL_Platform_H_


#include "../ModelBase.h"

#include "CloudCredential.h"
#include <cpprest/details/basic_types.h>
#include "Api.h"
#include "NewPlatform.h"

namespace io {
namespace github {
namespace cloudiator {
namespace rest {
namespace model {

/// <summary>
/// Representation of a platform used by Cloudiator
/// </summary>
class  Platform
    : public ModelBase
{
public:
    Platform();
    virtual ~Platform();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    void fromJson(web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    void fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// Platform members

    /// <summary>
    /// Human-readable name
    /// </summary>
    utility::string_t getName() const;
        void setName(utility::string_t value);
    /// <summary>
    /// PaaS stack type
    /// </summary>
    utility::string_t getType() const;
    bool typeIsSet() const;
    void unsetType();
    void setType(utility::string_t value);
    /// <summary>
    /// 
    /// </summary>
    std::shared_ptr<Api> getApi() const;
        void setApi(std::shared_ptr<Api> value);
    /// <summary>
    /// 
    /// </summary>
    std::shared_ptr<CloudCredential> getCredential() const;
        void setCredential(std::shared_ptr<CloudCredential> value);
    /// <summary>
    /// URI where the api of this platform provider can be accessed.
    /// </summary>
    utility::string_t getEndpoint() const;
    bool endpointIsSet() const;
    void unsetEndpoint();
    void setEndpoint(utility::string_t value);
    /// <summary>
    /// Unique identifier for the platform
    /// </summary>
    utility::string_t getId() const;
    bool idIsSet() const;
    void unsetId();
    void setId(utility::string_t value);

protected:
    utility::string_t m_Name;
        utility::string_t m_Type;
    bool m_TypeIsSet;
    std::shared_ptr<Api> m_Api;
        std::shared_ptr<CloudCredential> m_Credential;
        utility::string_t m_Endpoint;
    bool m_EndpointIsSet;
    utility::string_t m_Id;
    bool m_IdIsSet;
};

}
}
}
}
}

#endif /* IO_GITHUB_CLOUDIATOR_REST_MODEL_Platform_H_ */
