/**
 * Cloudiator REST Api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.2.0
 * Contact: daniel.baur@uni-ulm.de
 *
 * NOTE: This class is auto generated by the swagger code generator 2.3.0-SNAPSHOT.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/*
 * Task.h
 *
 * Represents a new task of a job. 
 */

#ifndef IO_GITHUB_CLOUDIATOR_REST_MODEL_Task_H_
#define IO_GITHUB_CLOUDIATOR_REST_MODEL_Task_H_


#include "../ModelBase.h"

#include "TaskType.h"
#include "Optimization.h"
#include <cpprest/details/basic_types.h>
#include "TaskInterface.h"
#include "Requirement.h"
#include <vector>
#include "Port.h"

namespace io {
namespace github {
namespace cloudiator {
namespace rest {
namespace model {

/// <summary>
/// Represents a new task of a job. 
/// </summary>
class  Task
    : public ModelBase
{
public:
    Task();
    virtual ~Task();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    void fromJson(web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    void fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// Task members

    /// <summary>
    /// Human-readable name. Uniquely identifies a task.
    /// </summary>
    utility::string_t getName() const;
        void setName(utility::string_t value);
    /// <summary>
    /// 
    /// </summary>
    std::vector<std::shared_ptr<Port>>& getPorts();
    bool portsIsSet() const;
    void unsetPorts();
    void setPorts(std::vector<std::shared_ptr<Port>> value);
    /// <summary>
    /// Interfaces of this task
    /// </summary>
    std::vector<std::shared_ptr<TaskInterface>>& getInterfaces();
    bool interfacesIsSet() const;
    void unsetInterfaces();
    void setInterfaces(std::vector<std::shared_ptr<TaskInterface>> value);
    /// <summary>
    /// 
    /// </summary>
    std::shared_ptr<Optimization> getOptimization() const;
    bool optimizationIsSet() const;
    void unsetOptimization();
    void setOptimization(std::shared_ptr<Optimization> value);
    /// <summary>
    /// 
    /// </summary>
    std::vector<std::shared_ptr<Requirement>>& getRequirements();
    bool requirementsIsSet() const;
    void unsetRequirements();
    void setRequirements(std::vector<std::shared_ptr<Requirement>> value);
    /// <summary>
    /// 
    /// </summary>
    std::shared_ptr<TaskType> getTaskType() const;
        void setTaskType(std::shared_ptr<TaskType> value);

protected:
    utility::string_t m_Name;
        std::vector<std::shared_ptr<Port>> m_Ports;
    bool m_PortsIsSet;
    std::vector<std::shared_ptr<TaskInterface>> m_Interfaces;
    bool m_InterfacesIsSet;
    std::shared_ptr<Optimization> m_Optimization;
    bool m_OptimizationIsSet;
    std::vector<std::shared_ptr<Requirement>> m_Requirements;
    bool m_RequirementsIsSet;
    std::shared_ptr<TaskType> m_TaskType;
    };

}
}
}
}
}

#endif /* IO_GITHUB_CLOUDIATOR_REST_MODEL_Task_H_ */
