/**
 * Cloudiator REST Api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.2.0
 * Contact: daniel.baur@uni-ulm.de
 *
 * NOTE: This class is auto generated by the swagger code generator 2.3.0-SNAPSHOT.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/*
 * Text.h
 *
 * Represents a string as valid json object 
 */

#ifndef IO_GITHUB_CLOUDIATOR_REST_MODEL_Text_H_
#define IO_GITHUB_CLOUDIATOR_REST_MODEL_Text_H_


#include "../ModelBase.h"

#include <cpprest/details/basic_types.h>

namespace io {
namespace github {
namespace cloudiator {
namespace rest {
namespace model {

/// <summary>
/// Represents a string as valid json object 
/// </summary>
class  Text
    : public ModelBase
{
public:
    Text();
    virtual ~Text();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    void fromJson(web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    void fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// Text members

    /// <summary>
    /// Content of the string
    /// </summary>
    utility::string_t getContent() const;
        void setContent(utility::string_t value);

protected:
    utility::string_t m_Content;
    };

}
}
}
}
}

#endif /* IO_GITHUB_CLOUDIATOR_REST_MODEL_Text_H_ */
