/**
 * Cloudiator REST Api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.2.0
 * Contact: daniel.baur@uni-ulm.de
 *
 * NOTE: This class is auto generated by the swagger code generator 2.3.0-SNAPSHOT.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */



#include "Tuple.h"

namespace io {
namespace github {
namespace cloudiator {
namespace rest {
namespace model {

Tuple::Tuple()
{
    m_Key = utility::conversions::to_string_t("");
    m_Value = utility::conversions::to_string_t("");
}

Tuple::~Tuple()
{
}

void Tuple::validate()
{
    // TODO: implement validation
}

web::json::value Tuple::toJson() const
{
    web::json::value val = web::json::value::object();

    val[utility::conversions::to_string_t("key")] = ModelBase::toJson(m_Key);
    val[utility::conversions::to_string_t("value")] = ModelBase::toJson(m_Value);

    return val;
}

void Tuple::fromJson(web::json::value& val)
{
    setKey(ModelBase::stringFromJson(val[utility::conversions::to_string_t("key")]));
    setValue(ModelBase::stringFromJson(val[utility::conversions::to_string_t("value")]));
}

void Tuple::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t("."))
    {
        namePrefix += utility::conversions::to_string_t(".");
    }

    multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t("key"), m_Key));
    multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t("value"), m_Value));
}

void Tuple::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t("."))
    {
        namePrefix += utility::conversions::to_string_t(".");
    }

    setKey(ModelBase::stringFromHttpContent(multipart->getContent(utility::conversions::to_string_t("key"))));
    setValue(ModelBase::stringFromHttpContent(multipart->getContent(utility::conversions::to_string_t("value"))));
}

utility::string_t Tuple::getKey() const
{
    return m_Key;
}


void Tuple::setKey(utility::string_t value)
{
    m_Key = value;
    
}
utility::string_t Tuple::getValue() const
{
    return m_Value;
}


void Tuple::setValue(utility::string_t value)
{
    m_Value = value;
    
}
}
}
}
}
}

