/**
 * Cloudiator REST Api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.2.0
 * Contact: daniel.baur@uni-ulm.de
 *
 * NOTE: This class is auto generated by the swagger code generator 2.3.0-SNAPSHOT.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */



#include "UserNew.h"

namespace io {
namespace github {
namespace cloudiator {
namespace rest {
namespace model {

UserNew::UserNew()
{
    m_Email = utility::conversions::to_string_t("");
    m_Password = utility::conversions::to_string_t("");
    m_PasswordRepeat = utility::conversions::to_string_t("");
}

UserNew::~UserNew()
{
}

void UserNew::validate()
{
    // TODO: implement validation
}

web::json::value UserNew::toJson() const
{
    web::json::value val = web::json::value::object();

    val[utility::conversions::to_string_t("email")] = ModelBase::toJson(m_Email);
    val[utility::conversions::to_string_t("password")] = ModelBase::toJson(m_Password);
    val[utility::conversions::to_string_t("passwordRepeat")] = ModelBase::toJson(m_PasswordRepeat);
    val[utility::conversions::to_string_t("tenant")] = ModelBase::toJson(m_Tenant);

    return val;
}

void UserNew::fromJson(web::json::value& val)
{
    setEmail(ModelBase::stringFromJson(val[utility::conversions::to_string_t("email")]));
    setPassword(ModelBase::stringFromJson(val[utility::conversions::to_string_t("password")]));
    setPasswordRepeat(ModelBase::stringFromJson(val[utility::conversions::to_string_t("passwordRepeat")]));
    std::shared_ptr<Tenant> newTenant(new Tenant());
    newTenant->fromJson(val[utility::conversions::to_string_t("tenant")]);
    setTenant( newTenant );
}

void UserNew::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t("."))
    {
        namePrefix += utility::conversions::to_string_t(".");
    }

    multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t("email"), m_Email));
    multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t("password"), m_Password));
    multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t("passwordRepeat"), m_PasswordRepeat));
    m_Tenant->toMultipart(multipart, utility::conversions::to_string_t("tenant."));
}

void UserNew::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t("."))
    {
        namePrefix += utility::conversions::to_string_t(".");
    }

    setEmail(ModelBase::stringFromHttpContent(multipart->getContent(utility::conversions::to_string_t("email"))));
    setPassword(ModelBase::stringFromHttpContent(multipart->getContent(utility::conversions::to_string_t("password"))));
    setPasswordRepeat(ModelBase::stringFromHttpContent(multipart->getContent(utility::conversions::to_string_t("passwordRepeat"))));
    std::shared_ptr<Tenant> newTenant(new Tenant());
    newTenant->fromMultiPart(multipart, utility::conversions::to_string_t("tenant."));
    setTenant( newTenant );
}

utility::string_t UserNew::getEmail() const
{
    return m_Email;
}


void UserNew::setEmail(utility::string_t value)
{
    m_Email = value;
    
}
utility::string_t UserNew::getPassword() const
{
    return m_Password;
}


void UserNew::setPassword(utility::string_t value)
{
    m_Password = value;
    
}
utility::string_t UserNew::getPasswordRepeat() const
{
    return m_PasswordRepeat;
}


void UserNew::setPasswordRepeat(utility::string_t value)
{
    m_PasswordRepeat = value;
    
}
std::shared_ptr<Tenant> UserNew::getTenant() const
{
    return m_Tenant;
}


void UserNew::setTenant(std::shared_ptr<Tenant> value)
{
    m_Tenant = value;
    
}
}
}
}
}
}

