/**
 * Cloudiator REST Api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.2.0
 * Contact: daniel.baur@uni-ulm.de
 *
 * NOTE: This class is auto generated by the swagger code generator 2.3.0-SNAPSHOT.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/*
 * VirtualMachineRequest.h
 *
 * Represents a request to create a new virtual machine. 
 */

#ifndef IO_GITHUB_CLOUDIATOR_REST_MODEL_VirtualMachineRequest_H_
#define IO_GITHUB_CLOUDIATOR_REST_MODEL_VirtualMachineRequest_H_


#include "../ModelBase.h"

#include <cpprest/details/basic_types.h>

namespace io {
namespace github {
namespace cloudiator {
namespace rest {
namespace model {

/// <summary>
/// Represents a request to create a new virtual machine. 
/// </summary>
class  VirtualMachineRequest
    : public ModelBase
{
public:
    VirtualMachineRequest();
    virtual ~VirtualMachineRequest();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    void fromJson(web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    void fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// VirtualMachineRequest members

    /// <summary>
    /// 
    /// </summary>
    utility::string_t getImage() const;
    bool imageIsSet() const;
    void unsetImage();
    void setImage(utility::string_t value);
    /// <summary>
    /// 
    /// </summary>
    utility::string_t getHardware() const;
    bool hardwareIsSet() const;
    void unsetHardware();
    void setHardware(utility::string_t value);
    /// <summary>
    /// 
    /// </summary>
    utility::string_t getLocation() const;
    bool locationIsSet() const;
    void unsetLocation();
    void setLocation(utility::string_t value);

protected:
    utility::string_t m_Image;
    bool m_ImageIsSet;
    utility::string_t m_Hardware;
    bool m_HardwareIsSet;
    utility::string_t m_Location;
    bool m_LocationIsSet;
};

}
}
}
}
}

#endif /* IO_GITHUB_CLOUDIATOR_REST_MODEL_VirtualMachineRequest_H_ */
