/**
 * Cloudiator REST Api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.2.0
 * Contact: daniel.baur@uni-ulm.de
 *
 * NOTE: This class is auto generated by the swagger code generator 2.3.0-SNAPSHOT.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/*
 * MiscApi.h
 *
 * 
 */

#ifndef IO_GITHUB_CLOUDIATOR_REST_API_MiscApi_H_
#define IO_GITHUB_CLOUDIATOR_REST_API_MiscApi_H_


#include "../ApiClient.h"

#include "InstallationRequest.h"

#include <boost/optional.hpp>

namespace io {
namespace github {
namespace cloudiator {
namespace rest {
namespace api {

using namespace io::github::cloudiator::rest::model;

class  MiscApi
{
public:
    MiscApi( std::shared_ptr<ApiClient> apiClient );
    virtual ~MiscApi();
    /// <summary>
    /// 
    /// </summary>
    /// <remarks>
    /// Installs Cloudiator tools on provided node
    /// </remarks>
    /// <param name="installRequest">a request to install the cloudiator tools on a provided node</param>
    pplx::task<void> installTools(
        std::shared_ptr<InstallationRequest> installRequest
    );

protected:
    std::shared_ptr<ApiClient> m_ApiClient;
};

}
}
}
}
}

#endif /* IO_GITHUB_CLOUDIATOR_REST_API_MiscApi_H_ */

