/**
 * Cloudiator REST Api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.2.0
 * Contact: daniel.baur@uni-ulm.de
 *
 * NOTE: This class is auto generated by the swagger code generator 2.3.0-SNAPSHOT.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/*
 * MonitoringApi.h
 *
 * 
 */

#ifndef IO_GITHUB_CLOUDIATOR_REST_API_MonitoringApi_H_
#define IO_GITHUB_CLOUDIATOR_REST_API_MonitoringApi_H_


#include "../ApiClient.h"

#include "Monitor.h"
#include <cpprest/details/basic_types.h>

#include <boost/optional.hpp>

namespace io {
namespace github {
namespace cloudiator {
namespace rest {
namespace api {

using namespace io::github::cloudiator::rest::model;

class  MonitoringApi
{
public:
    MonitoringApi( std::shared_ptr<ApiClient> apiClient );
    virtual ~MonitoringApi();
    /// <summary>
    /// 
    /// </summary>
    /// <remarks>
    /// Creates a monitor 
    /// </remarks>
    /// <param name="monitor">Monitor to be created </param>
    pplx::task<std::shared_ptr<Monitor>> addMonitor(
        std::shared_ptr<Monitor> monitor
    );
    /// <summary>
    /// 
    /// </summary>
    /// <remarks>
    /// Deletes the monitor identified by the given metric name. 
    /// </remarks>
    /// <param name="metric">Unique identifier of a monitor</param>
    pplx::task<void> deleteMonitor(
        utility::string_t metric
    );
    /// <summary>
    /// 
    /// </summary>
    /// <remarks>
    /// Returns all monitors visible to the user 
    /// </remarks>
    pplx::task<std::vector<std::shared_ptr<Monitor>>> findMonitors(
    );
    /// <summary>
    /// 
    /// </summary>
    /// <remarks>
    /// Retrieves the monitor with the given metric name 
    /// </remarks>
    /// <param name="metric">Unique identifier of a monitor</param>
    pplx::task<std::vector<std::shared_ptr<Monitor>>> getMonitor(
        utility::string_t metric
    );

protected:
    std::shared_ptr<ApiClient> m_ApiClient;
};

}
}
}
}
}

#endif /* IO_GITHUB_CLOUDIATOR_REST_API_MonitoringApi_H_ */

