/**
 * Cloudiator REST Api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.2.0
 * Contact: daniel.baur@uni-ulm.de
 *
 * NOTE: This class is auto generated by the swagger code generator 2.3.0-SNAPSHOT.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/*
 * UserApi.h
 *
 * 
 */

#ifndef IO_GITHUB_CLOUDIATOR_REST_API_UserApi_H_
#define IO_GITHUB_CLOUDIATOR_REST_API_UserApi_H_


#include "../ApiClient.h"

#include "Login.h"
#include "Tenant.h"
#include "Token.h"
#include "User.h"
#include "UserNew.h"

#include <boost/optional.hpp>

namespace io {
namespace github {
namespace cloudiator {
namespace rest {
namespace api {

using namespace io::github::cloudiator::rest::model;

class  UserApi
{
public:
    UserApi( std::shared_ptr<ApiClient> apiClient );
    virtual ~UserApi();
    /// <summary>
    /// 
    /// </summary>
    /// <remarks>
    /// Creates a new tenant 
    /// </remarks>
    /// <param name="tenant">Tenant creation request  (optional)</param>
    pplx::task<std::shared_ptr<Tenant>> createTenant(
        boost::optional<std::shared_ptr<Tenant>> tenant
    );
    /// <summary>
    /// 
    /// </summary>
    /// <remarks>
    /// Creates a new user 
    /// </remarks>
    /// <param name="user">User creation request  (optional)</param>
    pplx::task<std::shared_ptr<User>> createUser(
        boost::optional<std::shared_ptr<UserNew>> user
    );
    /// <summary>
    /// 
    /// </summary>
    /// <remarks>
    /// Authenticates a user 
    /// </remarks>
    /// <param name="login">User login request  (optional)</param>
    pplx::task<std::shared_ptr<Token>> login(
        boost::optional<std::shared_ptr<Login>> login
    );

protected:
    std::shared_ptr<ApiClient> m_ApiClient;
};

}
}
}
}
}

#endif /* IO_GITHUB_CLOUDIATOR_REST_API_UserApi_H_ */

